### ISSUE TITLE
[ Bug ] AssertionError: The NVIDIA driver on your system is too old (found version 10010)

### ISSUE THREAD

**Issue by ruanchaves** [izuna385/Dual-encoder-Entity-Retrieval-with-BERT#1]
I tried to run the basic example on the README.md of this repository under pytorch Docker containers ( both on CUDA 10 and CUDA 9 ).

I keep on getting the same error no matter what particular setup I choose:

```
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
```

I tried to run these containers on several distinct machines ( even on Google Cloud ). All of them had the latest NVIDIA drivers, so this error message doesn't make sense to me. 

Full traceback:

```
(myenv) root@79c9081baa1f:/home/repositories/Dual-encoder-Entity-Retrieval-with-BERT# CUDA_VISIBLE_DEVICES=0 python train.py -num_epochs 1

===PARAMETERS===
debug False
debug_for_entity_encoder False
dataset xxx
cached_instance False
lr 5e-06
weight_decay 1e-08
beta1 0.9
beta2 0.999
epsilon 1e-08
amsgrad False
word_embedding_dropout 0.1
scalingMSEfactor 1.0
save_model 1
cuda_devices 0
num_epochs 1
batch_size_for_train 32
batch_size_for_eval 32
allen_lazyload False
bert_name bert-base-uncased
max_context_len 80
max_mention_len 12
max_left_context_len 35
max_right_context_len 35
max_canonical_len 12
max_def_len 48
experiment_logdir ./experiment_logdir/
mention_dump_dir ./mention_dump_dir/
kbemb_dim 300
search_method_for_faiss_during_construct_smallKBfortrain cossim
negatives_for_knn 500
cand_num_for_knn 10000
model_for_training blink_implementation_inbatchencoder
biencoder_scoring cossim
negatives_during_train_fixednegatives_biencoder 15
cand_num_before_sort_candidates_forBLINKbiencoder 10000
search_method_before_re_sorting_for_faiss cossim
add_mse 0
===PARAMETERS END===

100%|##########| 231508/231508 [00:00<00:00, 343186.00B/s]
loading KB
set value and load original KB
original KB loaded
2it [00:00, 492.49it/s]
2it [00:00, 455.93it/s]

train statistics: 2 

100%|##########| 433/433 [00:00<00:00, 355129.77B/s]
100%|##########| 440473133/440473133 [01:43<00:00, 4244053.22B/s] 
100%|##########| 407873900/407873900 [01:08<00:00, 5982382.98B/s] 
Traceback (most recent call last):
  File "train.py", line 121, in <module>
    main()
  File "train.py", line 55, in main
    model = model.cuda()
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 458, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 458, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 186, in _lazy_init
    _check_driver()
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 77, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

```

**Comment by izuna385** [comment]
Thanks for your interest!
I checked versions of related packages, which is as the below.
```
torch                         1.2.0
transformers                  2.8.0
allennlp                      0.9.0
```
Could you give me the versions which you use? I'll try to upgrade package to the latest versions and debug codes.

**Comment by ruanchaves** [comment]
Thank you for your assistance. 

I installed **exactly** the same package versions you listed above, and now it works fine. I'm no longer getting weird nvidia driver errors.

```

(venv2) root@b049732753c9:/home/repositories/Dual-encoder-Entity-Retrieval-with-BERT# python3 train.py -num_epochs 1
Loading faiss with AVX2 support.
Loading faiss.

===PARAMETERS===
debug False
debug_for_entity_encoder False
dataset xxx
cached_instance False
lr 5e-06
weight_decay 1e-08
beta1 0.9
beta2 0.999
epsilon 1e-08
amsgrad False
word_embedding_dropout 0.1
scalingMSEfactor 1.0
save_model 1
cuda_devices 0
num_epochs 1
batch_size_for_train 32
batch_size_for_eval 32
allen_lazyload False
bert_name bert-base-uncased
max_context_len 80
max_mention_len 12
max_left_context_len 35
max_right_context_len 35
max_canonical_len 12
max_def_len 48
experiment_logdir ./experiment_logdir/
mention_dump_dir ./mention_dump_dir/
kbemb_dim 300
search_method_for_faiss_during_construct_smallKBfortrain cossim
negatives_for_knn 500
cand_num_for_knn 10000
model_for_training blink_implementation_inbatchencoder
biencoder_scoring cossim
negatives_during_train_fixednegatives_biencoder 15
cand_num_before_sort_candidates_forBLINKbiencoder 10000
search_method_before_re_sorting_for_faiss cossim
add_mse 0
===PARAMETERS END===

100%|##########| 231508/231508 [00:00<00:00, 451633.17B/s]
loading KB
set value and load original KB
original KB loaded
2it [00:00, 375.31it/s]
2it [00:00, 346.29it/s]

train statistics: 2 

100%|##########| 433/433 [00:00<00:00, 203374.43B/s]
100%|##########| 440473133/440473133 [01:13<00:00, 5954118.82B/s] 
100%|##########| 407873900/407873900 [01:18<00:00, 5224338.64B/s] 
accuracy: 0.5000, loss: 6.1127 ||: 100%|##########| 1/1 [00:00<00:00,  1.53it/s]
======Start encoding all entities in KB=====
======1. Start Tokenizing All Entities=====
======2. Encoding All Entities=====
100%|##########| 3/3 [00:00<00:00, 346.02it/s]
3it [00:00, 320.89it/s]0:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]======Encoding all entites from canonicals and definitions=====
100%|##########| 1/1 [00:00<00:00, 10.97it/s]
=====Encoding all entities in KB FINISHED!=====

+++++Indexnizing KB from encoded entites+++++
+++++Indexnizing KB from encoded entites FINISHED!+++++
Loading BLINKBiencoder
Loaded: BLINKBiencoder
Evaluation for BLINK start
============
<<<FINAL EVALUATION STARTS>>> dev Retrieve_Candidates: 100 
============
2it [00:00, 229.91it/s]
2it [00:00, 214.83it/s]
100%|##########| 1/1 [00:00<00:00, 19.92it/s]
============
<<<FINAL EVALUATION STARTS>>> test Retrieve_Candidates: 100 
============
2it [00:00, 184.35it/s]
2it [00:00, 175.05it/s]
100%|##########| 1/1 [00:00<00:00, 21.80it/s]
result_dir:  ./experiment_logdir/200812_183001/
Experiment time 194 sec
```

**Comment by izuna385** [comment]
Thanks for your report. I'll fix README.md.
